import { z } from 'zod';

const objectIdRegex = /^[0-9a-fA-F]{24}$/;

export const leaveSchema = z.object({
  _id: z.string().regex(objectIdRegex).optional(), // usually generated by MongoDB
  employeeId: z.string().regex(objectIdRegex, "Invalid ObjectId for employeeId"),
  type: z.enum(['Annuel', 'Maladie', 'Non payé', 'Autre']),
  startDate: z.string().refine(d => !isNaN(Date.parse(d)), {
    message: "Invalid startDate format"
  }),
  endDate: z.string().refine(d => !isNaN(Date.parse(d)), {
    message: "Invalid endDate format"
  }),
  days: z.preprocess(
    (val) => (val === '' || val === undefined ? undefined : Number(val)),
    z.number().min(0.5, "Minimum 0.5 jour").optional(),
  ),
  reason: z.string().optional(),
  status: z.enum(['En attente', 'Approuvé', 'Rejeté', 'Annulé']).default('En attente'),
  rejectionReason: z.string().optional(),
});

/**
 * Recursively extracts all leaf paths in dot notation.
 * Example: ['firstName', 'lastName', ..., 'salaryInfo.baseSalary', 'salaryInfo.currency', ...]
 */
export function getLeafFieldPaths(schema, prefix = '') {
  if (schema instanceof z.ZodObject) {
    const shape = schema.shape;
    let paths = [];
    for (const key in shape) {
      const subSchema = shape[key];
      const newPrefix = prefix ? `${prefix}.${key}` : key;
      if (subSchema instanceof z.ZodObject) {
        // Recurse into nested object
        paths = paths.concat(getLeafFieldPaths(subSchema, newPrefix));
      } else {
        paths.push(newPrefix);
      }
    }
    return paths;
  }
  return [];
}

// All available leaf paths that can appear in a column header
export const LEAVE_LEAF_FIELDS = getLeafFieldPaths(leaveSchema);